mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itembank.urls')),
    path('', include('testbuilder.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

testbuilder/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'testbuilder'
urlpatterns = [
    # ex: /itembank/
    path('', views.index, name='tests'),
    path('testbuilder/', views.index, name='tests'),
    path('ajax/selected_test/', views.selected_test, name='selected_test'),
]

testbuilder/templates/testbuilder/index.html
{% load render_table from django_tables2 %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static "static_jquery/js/jquery.js" %}"></script>
    <meta charset="UTF-8">
    <title>Itembank Index</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/testbuilder.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col"><h1 align="center">Test Builder Index</h1></div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="container-fluid">
                <div class="row">
                    <h3>Unpublished Tests</h3>
                    {% render_table table %}
                </div>
                <div class="row">
                    <h3>Published Tests</h3>
                </div>
            </div>

        </div>
        <div class="col">
            <h3>Test Preview</h3>
            <div class="shadow">
                <p id="demo"></p>
            </div>
        </div>
    </div>
</div>

  <script>
      $(document).ready(function () {
          $('.shadow').hide();
          $('#select_button').on('click', function() {
              $('.shadow').show("slow");
              var test_id = $(this).attr("name");
              var $demo = $('#demo');
              $.ajax({
                  url: '{% url "testbuilder:selected_test" %}',
                  data: {
                      'test_id': test_id
                  },
                  dataType: 'json',
                  success: function(test_items) {
                      $.each(test_items, function(item, description){
                          $demo.append("<h4>" + item + "</h4>");
                          switch(item){
                              case 'multiple choice items':
                                  $.each(description, function (item_no, content) {
                                      $demo.append(content.rubric + "<br>" +
                                          "<li>" + content.option1 + "</li>" +
                                          "<li>" + content.option2 + "</li>" +
                                          "<li>" + content.option3 + "</li>")
                                  });
                                  break;
                              case 'short text items':
                                  $.each(description, function (item_no, content) {
                                      $demo.append(content.rubric + "<br>")
                                  });
                          }
                      });
                  }
              });
          });
      });

  </script>

</body>
</html>