itembank/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'itembank'
urlpatterns = [
    # ex: /itembank/
    path('', views.index, name='index'),
    path('itembank/', views.index, name='index'),
    # ex: /itembank/MultipleChoiceItem/
    path('itembank/MultipleChoiceItem/', views.display_items_MC, name='display_MC'),
    path('itembank/ShortTextItem/', views.display_items_ST, name='display_ST'),
    path('itembank/LongTextItem/', views.display_items_LT, name='display_LT'),
    # ex: /itembank/MultipleChoiceItem/5
    path('itembank/MultipleChoiceItem/<int:question_id>/', views.detail_MC, name='detail_MC'),
    path('itembank/ShortTextItem/<int:question_id>/', views.detail_ST, name='detail_ST'),
    path('itembank/LongTextItem/<int:question_id>/', views.detail_LT, name='detail_LT'),
    path('itembank/MultipleChoiceItem/<int:id>', views.edit_item_MC, name='edit_item_MC'),
    path('itembank/ShortTextItem/<int:id>', views.edit_item_ST, name='edit_item_ST'),
    path('itembank/ShortTextItem/<int:id>', views.edit_item_LT, name='edit_item_LT'),
    # ex: /;itembank/MultipleChoiceItem/new
    path('itembank/ShortTextItem/new_item', views.new_item_ST, name='new_item_ST'),
    path('itembank/MultipleChoiceItem/new_item', views.new_item_MC, name='new_item_MC'),
    path('itembank/LongTextItem/new_item', views.new_item_LT, name='new_item_LT'),
]
'''
    accounts/ login/ [name='login'] #works
    accounts/ logout/ [name='logout'] #works
    accounts/ password_change/ [name='password_change'] #goes to django admin
    accounts/ password_change/done/ [name='password_change_done'] # goes to django admin
    accounts/ password_reset/ [name='password_reset'] #works
    accounts/ password_reset/done/ [name='password_reset_done'] #works but link doesn't from pass
    accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm'] 
    accounts/ reset/done/ [name='password_reset_complete'] #works after adding itembank: to url

#Add Django site authentication urls (for login, logout, password management)
#app_name = ''
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
'''

mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itembank.urls')),
    path('', include('testbuilder.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

itembank/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class CEFRLevel(models.Model):
    cefr_level = models.CharField(max_length=2)
    descripion = models.CharField(max_length=1000)
    def __str__(self):
        return self.cefr_level

class SkillSystem(models.Model):
    name = models.CharField(max_length=20)
    skill = models.BooleanField(default=False)
    system = models.BooleanField(default=False)
    def __str__(self):
        return self.name

class MultipleChoiceItem(models.Model):
    OPTION_ANSWER = (
        ('1', 'Option 1'),
        ('2', 'Option 2'),
        ('3', 'Option 3')
    )
    rubric = models.CharField(max_length=250)
    option1 = models.CharField(max_length=50)
    option2 = models.CharField(max_length=50)
    option3 = models.CharField(max_length=50)
    answer = models.CharField(max_length=1, choices=OPTION_ANSWER)
    level = models.ForeignKey(CEFRLevel, on_delete=models.CASCADE)
    language = models.ForeignKey(SkillSystem, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.rubric

class ShortTextItem(models.Model):
    rubric = models.CharField(max_length=400)
    word_limit = models.IntegerField(
        default=10,
        validators=[MaxValueValidator(250), MinValueValidator(10)])
    level = models.ForeignKey(CEFRLevel, on_delete=models.CASCADE)
    language = models.ForeignKey(SkillSystem, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.rubric


class LongTextItem(models.Model):
    rubric = models.CharField(max_length=400)
    word_limit = models.IntegerField(
        default=250,
        validators=[MaxValueValidator(2500), MinValueValidator(10)])
    level = models.ForeignKey(CEFRLevel, on_delete=models.CASCADE)
    language = models.ForeignKey(SkillSystem, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.rubric

itembank/forms.py
from django import forms
from .models import MultipleChoiceItem, ShortTextItem, LongTextItem

class MultipleChoiceItemForm(forms.ModelForm):
    class Meta:
        model = MultipleChoiceItem
        exclude = ['pub_date']
        verbose_name = "Multiple Choice Item"
        widgets = {
            'rubric': forms.Textarea(attrs={'cols': 80, 'rows': 2}),
        }

class ShortTextItemForm(forms.ModelForm):
    class Meta:
        model = ShortTextItem
        fields = '__all__'
        verbose_name = "Short Response Item"

class LongTextItemForm(forms.ModelForm):
    class Meta:
        model = LongTextItem
        fields = '__all__'
        verbose_name = "Long Response Item"

itembank/views.py
from django.apps import apps
from django_tables2 import RequestConfig
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import *
from .tables import *
from .models import MultipleChoiceItem, ShortTextItem, LongTextItem

# class created to avoid code repetition in new item views
class NewItem:

    def __init__(self, form_type, request):
        self.form_name = form_type.__name__
        if request.method == "POST":
            self.form = form_type(request.POST)
            self.post = self.form.save(commit=False)
            self.post.pub_date = timezone.now()
            self.post.save()
            if form_type == MultipleChoiceItemForm:
                self.codes = { self.form_name: 'itembank:detail_MC' }
            elif form_type == ShortTextItemForm:
                self.codes = { self.form_name: 'itembank:detail_ST' }
            elif form_type == LongTextItemForm:
                self.codes = { self.form_name: 'itembank:detail_LT' }
            self.return_msg = redirect(self.codes.get(self.form_name), question_id=self.post.pk)
        else:
            self.return_msg = render(request, 'itembank/new_item.html', {'form': form_type()})

    def return_page(self):
        return self.return_msg

def new_item_MC(request):
    return NewItem(MultipleChoiceItemForm, request).return_page()

def new_item_ST(request):
    return NewItem(ShortTextItemForm, request).return_page()

def new_item_LT(request):
    return NewItem(LongTextItemForm, request).return_page()

# edit item views are accessed from index table
def edit_item_MC(request, id):
    item = MultipleChoiceItem.objects.get(pk=id)
    if request.method == "POST":
        form = MultipleChoiceItemForm(request.POST, instance=item)
        form.pub_date = timezone.now()
        form.save()
        return redirect('itembank:detail_MC', question_id=item.pk)
    else:
        form = MultipleChoiceItemForm(instance=item)
        return render(request, 'itembank/new_item.html', {'form': form})

def edit_item_ST(request, id):
    item = ShortTextItem.objects.get(pk=id)
    if request.method == "POST":
        form = ShortTextItemForm(request.POST, instance=item)
        form.pub_date = timezone.now()
        form.save()
        return redirect('itembank:detail_ST', question_id=item.pk)
    else:
        form = ShortTextItemForm(instance=item)
        return render(request, 'itembank/new_item.html', {'form': form})

def edit_item_LT(request, id):
    item = LongTextItem.objects.get(pk=id)
    if request.method == "POST":
        form = ShortTextItemForm(request.POST, instance=item)
        form.pub_date = timezone.now()
        form.save()
        return redirect('itembank:detail_LT', question_id=item.pk)
    else:
        form = LongTextItemForm(instance=item)
        return render(request, 'itembank/new_item.html', {'form': form})

# index page data display, could be optimised better but works
@login_required
def index(request):
    # takes all models from itembank
    app_models = apps.all_models['itembank']
    item_models = {}
    non_item_models = {}
    # key is model name lowercase, value is the model
    for key, value in app_models.items():
        # seperates item models from level and skill models
        if "item" in key:
            #item_models[key] = value
            item_models[str(value._meta.verbose_name_plural)] = value
        else:
            non_item_models[str(value._meta.verbose_name_plural)] = value

    # extracts only cefr levels, not skills from non_items
    # and place them in a list called levels_and_skills
    levels_and_skills = [ b for name, type in non_item_models.items()
                         if 'cefr' in name for b in type.objects.all() ]

    # extract the data in item_models
    count_output = {}
    for key, model in item_models.items():
        count_output[key] = { str(x):model.objects.filter(level__cefr_level=str(x)).count()
                      for x in levels_and_skills }

    return render(request, 'itembank/index.html', {'count_output': count_output})

# class created to reduce code repetition in display_items views
class DefineItem:
    def __init__(self, item_type, item_table, item_code):
        self.item_type = item_type
        self.item_table = item_table
        self.get_table = item_table(item_type.objects.order_by('id'))
        self.context = {
            'table': self.get_table,
            'list_count': item_type.objects.count(),
            'header': str(item_type._meta.verbose_name_plural),
            'specific_url': ('itembank:new_item_'+item_code)
        }

    def produce_table(self, request, number_items):
        self.a_table = RequestConfig(request, paginate={'per_page': number_items}).configure(self.get_table)

# displays all items of a given item type
# item type is passed in the url
def display_items_MC(request):
    item = DefineItem(MultipleChoiceItem, MultipleChoiceItemTable, 'MC')
    item.produce_table(request, 10)
    return render(request, 'itembank/disply_items.html', (item.context))

def display_items_ST(request):
    item = DefineItem(ShortTextItem, ShortTextItemTable, 'ST')
    item.produce_table(request, 5)
    return render(request, 'itembank/disply_items.html', (item.context))

def display_items_LT(request):
    item = DefineItem(LongTextItem, LongTextItemTable, 'ST')
    item.produce_table(request, 5)
    return render(request, 'itembank/disply_items.html', (item.context))

# display specifics of an item when it has been clicked on
def detail_MC(request, question_id):
    question_object = get_object_or_404(MultipleChoiceItem, pk=question_id)
    header = str(MultipleChoiceItem._meta.verbose_name)
    context = {
        'question_object': question_object,
        'header': header,
    }
    return render(request, 'itembank/detail.html', (context))

def detail_ST(request, question_id):
    question_object = get_object_or_404(ShortTextItem, pk=question_id)
    header = str(ShortTextItem._meta.verbose_name)
    context = {
        'question_object': question_object,
        'header': header,
    }
    return render(request, 'itembank/detail.html', (context))

def detail_LT(request, question_id):
    question_object = get_object_or_404(LongTextItem, pk=question_id)
    header = str(LongTextItem._meta.verbose_name)
    context = {
        'question_object': question_object,
        'header': header,
    }
    return render(request, 'itembank/detail.html', (context))

itembank/templates/itembank/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ header|capfirst }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/itembank.css' %}">
    <!-- fontawesome - need to check out -->
    <script defer src="{% static 'fontawesome/js/fontawesome-all.min.js' %}"></script>
</head>

<body>

     <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'itembank:index' %}">Item Bank</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
          {% if user.is_authenticated %}
              <li class="nav-item text-nowrap"><a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a></>
          {% else %}
              <li class="nav-item text-nowrap"><a  class="nav-link"href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
      </ul>
    </nav>


    <div class="container-fluid">
      <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          {% if user.is_authenticated %}
              User: {{ user.get_username }}
          {% endif %}
          <div class="sidebar-sticky">
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>By Item Type</span>
              <a class="d-flex align-items-center text-muted" href="#">
                  <span data-feather="plus-circle"></span>
              </a>
          </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'itembank:display_MC' %}">
                  <span data-feather="file-text"></span>
                  Multiple Choice
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'itembank:display_ST' %}">
                  <span data-feather="file-text"></span>
                  Short Text Response
                </a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'itembank:display_LT' %}">
                  <span data-feather="file-text"></span>
                  Long Text Response
                </a>
              </li>
            </ul>
          </div>
      </nav>
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">


    {% block content %}
    {% endblock %}
        </main>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <!-- this caused problems, is not part of bootstrap bundle below
    <script src="../../assets/js/vendor/popper.min.js"></script>
    -->
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
     <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!--clickable row script -->
     <script>jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
        window.location = $(this).data("href");
        });
    });</script>
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

  </body>
</html>

itembank/templates/itembank/detail.html
{% extends 'itembank/base.html' %}

{% block content %}
    <h1>{{ header|capfirst }}</h1>
    <h2>Question ID: {{ question_object.id }} || Level: {{ question_object.level }} || {{ question_object.language }}</h2>
    <h3>{{ question_object.rubric }}</h3>
    <ol type="1">
        <li>{{ question_object.option1 }}</li>
        <li>{{ question_object.option2 }}</li>
        <li>{{ question_object.option3 }}</li>
    </ol>
    <h4>Answer: {{ question_object.answer }}</h4>

{% endblock %}

itembank/templates/itembank/disply_items.html
{% extends 'itembank/base.html' %}
{% load render_table from django_tables2 %}

{% block content %}

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2">{{ header|capfirst }}</h1>
             <div class="btn-group mr-2">
                 <a href="{% url specific_url %}">
                    <button class="btn btn-sm btn-outline-secondary">Add an item</button>
                </a>
            </div>
        </div>
        Total number of items: {{ list_count }}
        {% render_table table %}


{% endblock %}

itembank/templates/itembank/index.html
{% extends 'itembank/base.html' %}

{% block content %}

    <div id="container"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Item Bank Index Page</h1>
    </div>
    <div class="row justify-content-center">
    <div class="col-8">

    {% for key, value in count_output.items %}
        <table  class="table table-bordered table-sm">
        <thead class="thead-dark">
        <tr>
            <th scope="row">
                <h4>{{ key|capfirst }}</h4>
            </th>
        </tr>
        </thead>
        <tr><td>
        <table style="width:100%">
            <tr>

                {% for key2, value2 in value.items %}
                    <td class="table-active"><h5>{{ key2 }}</h5></td>
                    <td><h5>{{ value2 }}</h5></td>
                    <td>&nbsp;&nbsp</td>
                {% endfor %}

            </tr>
        </table>
        </td></tr>
        </table>
        <div id='{{ key }}'></div>
        <script>
        Highcharts.chart('{{ key }}', {
            chart: {
                type: 'column'
            },
            title: {
                text: '{{ key|capfirst }}'
            },
            xAxis: {
                categories: [
                    {% for key2, value2 in value.items %}
                        '{{ key2 }}',
                    {% endfor %}
                        ],
                title: {
                    enabled: true,
                    text: 'CEFR Level',
                    style: {
                        fontWeight: 'normal'
                    }
                }
            },
            yAxis: {
                title: {
                    enabled: true,
                    text: 'Items created',
                    style: {
                        fontWeight: 'normal'
                    }
                }
            },
            series: [{
                showInLegend: false,
                name: 'Items Created',
                data: [{% for key2, value2 in value.items %}{{ value2 }},{% endfor %}]
            },
            ]
        });
        </script>

    {% endfor %}
    </div>
    </div>
{% endblock %}

itembank/templates/itembank/new_item.html
{% extends 'itembank/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-8">
    <h1>New {{ form.Meta.verbose_name }}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        <table class="table table-bordered table-sm">
            <tbody>
                {{ form.as_table }}
            </tbody>
        </table>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    </div>
</div>
{% endblock %}